[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015A3B7B71A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015A3B7B74D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /wd/hub/status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000015A3B7B7650>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /wd/hub/status